#pragma once

// Preferences dialog
#define IDD_PREFERENCES             101

// Preferences controls
#define IDC_SAVE_FILENAME           1001
#define IDC_OVERWRITE_BEHAVIOR      1002
#define IDC_JPEG_QUALITY            1003
#define IDC_REQUEST_TIMEOUT         1005
#define IDC_STATIC_FILENAME         1012
#define IDC_STATIC_QUALITY          1013
#define IDC_STATIC_TIMEOUT          1014
#define IDC_INCLUDE_BACK_COVERS     1006
#define IDC_INCLUDE_ARTIST_IMAGES   1007
#define IDC_BACK_COVER_FILENAME     1008
#define IDC_ARTIST_IMAGE_FILENAME   1009
#define IDC_STATIC_BACK_FILENAME    1016
#define IDC_STATIC_ARTIST_FILENAME  1017
#define IDC_SAVE_FORMAT             1010
#define IDC_STATIC_FORMAT           1018
#define IDC_NETEASE_MAX_RESULTS     1020
#define IDC_ITUNES_MAX_RESULTS      1021
#define IDC_DEEZER_MAX_RESULTS      1022
#define IDC_LASTFM_MAX_RESULTS      1023
#define IDC_MUSICBRAINZ_MAX_RESULTS 1024
#define IDC_DISCOGS_MAX_RESULTS     1025

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
